#Estrutura de dados em Json

In [38]:
import json 

data = {
    'nome': 'joao',
    'idade' : 20,
    'cidade' : 'sao paulo'
}
data

{'nome': 'joao', 'idade': 20, 'cidade': 'sao paulo'}

#Escrever dados

In [39]:
with open ('exemplo_json.json','w') as json_file:
    json.dump(data, json_file)

#Ler dados

In [40]:
with open ('exemplo_json.json', 'r') as json_file:
    df_json = json.load(json_file)

In [41]:
import pandas as pd

data = {
    'nome': ['ana', 'Gabriel', 'Pedro', 'Maria', 'Camila'],
    'idade': [20,30,40,12,30],
    'cidade': ['Sao Paulo', 'Fortaleza', 'Rio de Janeiro', 'Boston', 'Rio']
}

df_csv = pd.DataFrame(data)
df_csv.to_csv('exemplo_csv.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'exemplo_csv.csv'

#Lendo CSV

In [32]:
df_csv = pd.read_csv('exemplo_csv.csv')
df_csv

      nome  idade          cidade
0      ana     20       Sao Paulo
1  Gabriel     30       Fortaleza
2    Pedro     40  Rio de Janeiro
3    Maria     12          Boston
4   Camila     30             Rio

#Estrutura de dados em Excel

In [44]:
data = {
    'nome': ['ana', 'Gabriel', 'Pedro', 'Maria', 'Camila'],
    'idade': [20,30,40,12,30],
    'cidade': ['Sao Paulo', 'Fortaleza', 'Rio de Janeiro', 'Boston', 'Rio']
}

df_excel = pd.DataFrame(data)
df_excel.to_excel('exemplo_excel.', index=False) #Este index false é importante

#Exercicio 1 - Crie uma estrutura em python para salvar os dados abaixo nas seguintes estruturas: json, excel e csv. apos isso ler as informacoes

In [65]:
informacoes = {
    'nome' : ['Maria', 'Ricardo', 'Gabriel', 'Lorran'],
    'profissao' : ['Medica', 'Doutor', 'Cantor', 'Programador'],
    'idade' : [48, 29, 30, 18],
    'sexo' : ['F', 'M', 'M', 'M']
}

df_excel = pd.DataFrame(informacoes)
df_excel.to_excel('informacoes_excel.xlsx', index=False)

df_csv = pd.DataFrame(informacoes)
df_csv.to_csv('informacoes_csv.csv', index=False)
df_csv = pd.read_csv('informacoes_csv.csv')
df_csv

with open ('informacoes_json.json','w') as json_file:
    json.dump(informacoes, json_file) 
    
with open ('informacoes_json.json', 'r') as json_file:
    df_json = json.load(json_file)

df_csv

      nome    profissao  idade sexo
0    Maria       Medica     48    F
1  Ricardo       Doutor     29    M
2  Gabriel       Cantor     30    M
3   Lorran  Programador     18    M

In [66]:
df_json

{'nome': ['Maria', 'Ricardo', 'Gabriel', 'Lorran'],
 'profissao': ['Medica', 'Doutor', 'Cantor', 'Programador'],
 'idade': [48, 29, 30, 18],
 'sexo': ['F', 'M', 'M', 'M']}

In [62]:
data_sice = pd.read_csv(r'D:\Python\NovaAulaPython\SegundoSemestre\Aula11\informacoes_csv.csv')
data_sice

      nome    profissao  idade sexo
0    Maria       Medica     48    F
1  Ricardo       Doutor     29    M
2  Gabriel       Cantor     30    M
3   Lorran  Programador     18    M

In [68]:
for i in range(len(df_csv)):
    print(f'Nome:{df_csv['nome'][i]}, idade:, {df_csv['idade'][i]}')

Nome:Maria, idade:, 48
Nome:Ricardo, idade:, 29
Nome:Gabriel, idade:, 30
Nome:Lorran, idade:, 18

In [71]:
i= 0
while i < len(df_csv["nome"]):
    print(f"Nome: {df_csv['nome'][i]}, Idade: {df_csv['idade'][i]}, Profissão: {df_csv['profissao'][i]}, Sexo: {df_csv['sexo'][i]}")
    i += 1

Nome: Maria, Idade: 48, Profissão: Medica, Sexo: F
Nome: Ricardo, Idade: 29, Profissão: Doutor, Sexo: M
Nome: Gabriel, Idade: 30, Profissão: Cantor, Sexo: M
Nome: Lorran, Idade: 18, Profissão: Programador, Sexo: M

In [74]:
def buscar_info(nome, data):
    if nome in data["nome"]:
        index = data["nome"].index(nome)
        return f"Nome: {nome}, Idade: {data['idade'][index]}, Profissão: {data['profissao'][index]}"
    else:
        return "Nome não encontrado."

print(buscar_info("Gabriel", informacoes))

Nome: Gabriel, Idade: 30, Profissão: Cantor

In [82]:
calcular_media = lambda idades: sum(idades) / len(idades)

print(f"A média é: {calcular_media(df_csv['idade'])}")

A média é: 31.25